# Generated by Django 5.0.1 on 2024-10-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
